### PR TITLE
InterOp API v1.0 pull request

### PR DESCRIPTION
**Pull request by interconn-pec**
API specification for interconnection of privacy computing systems.

### CODE REVIEW

**Review by shaojian-ant — APPROVED** [review]
LGTM

**Comment by shaojian-ant** [comment]
请评论这句话：I have read the CLA Document and I hereby sign the CLA

**Comment by interconn-pec** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by interconn-pec** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
